../../../pyodbc.pyi,sha256=OyamEtV9aa_aLnpAFRoYy9bckoPEDzNPZNmKdLGE2no,11518
pyodbc-4.0.31.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
pyodbc-4.0.31.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.31.dist-info/METADATA,sha256=B_fPInXAwsQa-U4AkdbzdWXHVye-BB6jCdSXEMHSbVA,2173
pyodbc-4.0.31.dist-info/RECORD,,
pyodbc-4.0.31.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pyodbc-4.0.31.dist-info/WHEEL,sha256=jR_DIfh0YPrTez7i3YqBzGYuKdVs75FjZMdMtvIwioM,103
pyodbc-4.0.31.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc.cpython-39-x86_64-linux-gnu.so,sha256=6eZBhLisCvn2uNvsDBud0r2SVBfHFIPfKHBYa5bi1NE,812296
